resize_shape: [256, 256]
targets: ['person', 'no person']
model_path: "cctv_detection.h5"
model_url: "https://github.com/CVxTz/FastImageClassification/releases/download/v0.1/image_classification.h5"
model_sha256: "d5cd9082651faa826cab4562f60e3095502286b5ea64d5b25ba3682b66fbc305"